# Generated by Django 4.2.16 on 2026-03-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='external_url',
            field=models.URLField(blank=True, help_text='External link (e.g. credential URL). Used only if no image is uploaded.'),
        ),
        migrations.AddField(
            model_name='certification',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload certificate image (shown in lightbox)', null=True, upload_to='certifications/'),
        ),
    ]
