# Generated by Django 4.2.16 on 2026-03-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_certification_external_url_certification_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='external_url',
        ),
        migrations.AddField(
            model_name='certification',
            name='link',
            field=models.URLField(blank=True, help_text='External verification URL. If both image and link are set, image opens in lightbox AND a link button appears.'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a scan/photo of the certificate', null=True, upload_to='certifications/'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
