# Generated by Django 4.2.16 on 2026-03-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_certification_external_url_certification_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone / WhatsApp'), ('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('website', 'Website'), ('other', 'Other')], max_length=20)),
                ('label', models.CharField(help_text='Display text e.g. yahiaAlg', max_length=100)),
                ('url', models.CharField(help_text='Full URL or value (mailto:, tel:, https://...)', max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('show_on_cv', models.BooleanField(default=True, help_text='Include in print CV')),
            ],
            options={
                'verbose_name': 'Contact Link',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(help_text='e.g. Native, B2 Upper-Intermediate', max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Lakhfif Yahia Abderraouf', max_length=200)),
                ('job_title', models.CharField(default='Full-Stack Developer · Data Engineer', max_length=200)),
                ('summary', models.TextField(help_text='Short bio shown on CV and portfolio hero')),
                ('location', models.CharField(default='Sétif, Algeria', max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
            options={
                'verbose_name': 'Site Profile',
                'verbose_name_plural': 'Site Profile',
            },
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Organiser / institution', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Topics covered, comma-separated is fine')),
                ('period', models.CharField(help_text='e.g. 2023–2024 or May 2024', max_length=60)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='training/')),
                ('link', models.URLField(blank=True, help_text='Verification or course URL')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='certification',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload scan/photo of certificate', null=True, upload_to='certifications/'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='link',
            field=models.URLField(blank=True, help_text='External verification URL'),
        ),
    ]
