# Generated by Django 4.2.16 on 2026-03-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_contactlink_language_siteprofile_trainingcourse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='cv_file',
            field=models.FileField(blank=True, help_text='Upload your CV as PDF or DOCX for the Download button', null=True, upload_to='cv/'),
        ),
    ]
